//! Type archives — bundled databases of function prototypes and named types
//! used by the decompiler to recover typed parameters, return values, and
//! stack layouts.
//!
//! # Overview
//!
//! A [`TypeArchive`] is a postcard-serialized blob shipped under `types/` in
//! the repository root. Archives are generated by the `tools/typegen` crate
//! (out-of-workspace, maintainer-only — see `types/README.md`) from upstream
//! Rust binding crates like `windows-sys` and `libc`. At runtime they are
//! looked up by stem via [`load_embedded`]; the format+architecture → stem
//! mapping lives in `reghidra-core::project` where `BinaryInfo` is defined,
//! since `reghidra-decompile` sits below `reghidra-core` in the crate graph
//! and can't see `BinaryFormat` / `Architecture` directly.
//!
//! # Phase 5c layering
//!
//! This module lives in `reghidra-decompile` rather than `reghidra-core`
//! so that [`crate::DecompileContext`] can carry an optional
//! `Arc<TypeArchive>` without creating a cyclic dependency. The data
//! model, the on-disk format, and the embedded-file lookup are defined
//! here; the `BinaryInfo`-aware dispatch is a thin wrapper in
//! `reghidra-core::project`.
//!
//! Consumers — arity capping for the stack-arg collapser, typed `VarDecl`
//! emission, return-type propagation, the right-click "Set Type" retype
//! UI — are wired up in later PRs of Phase 5c. PR 1 shipped the module
//! with zero behavioral impact so the scaffolding could land
//! independently; PR 2 relocates it and exposes it on `DecompileContext`
//! without consuming it.

pub mod archive;

use include_dir::{include_dir, Dir};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;

pub use archive::ArchiveError;

/// Embedded type archives. Same include_dir pattern as `bundled_sigs` so the
/// archives travel inside the binary and there's no runtime filesystem lookup.
/// The directory may be empty in early Phase 5c PRs — that's fine, the loader
/// just returns an empty vec.
static TYPES_DIR: Dir<'_> = include_dir!("$CARGO_MANIFEST_DIR/../../types");

// ---------------------------------------------------------------------------
// Data model
// ---------------------------------------------------------------------------

/// A bundled type archive. Keyed lookups let the decompiler resolve a call
/// target's prototype in O(1) and a named type reference (from another
/// prototype's arg list) in O(1) without traversing a dependency graph.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct TypeArchive {
    /// Human-readable name of the archive (e.g. `"windows-x64"`). Used in
    /// status strings and log output, not in lookup keys.
    pub name: String,
    /// Monotonic archive format version. Bumped when the wire format changes
    /// in a way that isn't backwards-compatible via serde defaults; the
    /// loader refuses archives whose version is newer than [`ARCHIVE_VERSION`]
    /// so old binaries fail fast on mismatched data files.
    pub version: u32,
    /// Canonical function name → prototype. The key is whatever string the
    /// decompiler will use to look up the prototype at a call site: for C
    /// it's the bare symbol; for C++ it's the mangled name so mangled
    /// imports resolve without going through the demangler.
    pub functions: HashMap<String, FunctionType>,
    /// Named type aliases, structs, unions, enums referenced by
    /// [`TypeRef::Named`] from within the archive.
    pub types: HashMap<String, TypeDef>,
}

/// Current archive format version. See [`TypeArchive::version`].
pub const ARCHIVE_VERSION: u32 = 1;

/// A function prototype.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FunctionType {
    /// Canonical function name — same string as the key in
    /// [`TypeArchive::functions`]. Duplicated here so iterators over the
    /// prototype values don't have to carry the key alongside.
    pub name: String,
    /// Fixed arguments in declaration order. Variadic tail (for `printf`
    /// etc.) is signaled by [`Self::is_variadic`], not by a sentinel entry.
    pub args: Vec<ArgType>,
    /// Return type. `void` is represented as
    /// `TypeRef::Primitive(Primitive::Void)`, never `None`, to keep the
    /// decompiler's type-propagation pass from having to special-case absence.
    pub return_type: TypeRef,
    /// ABI / calling convention. Important for x86-32 where cdecl/stdcall
    /// distinction affects stack cleanup semantics; irrelevant on x86-64
    /// SysV / Win64 where there's effectively one convention per platform.
    pub calling_convention: CallingConvention,
    /// Whether the function accepts a variadic tail after its fixed args.
    /// The arity-capping pass (PR 4) uses this to decide whether to truncate
    /// pending stack-pushed arguments at `args.len()` or leave them alone.
    pub is_variadic: bool,
}

/// A single argument in a function prototype.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ArgType {
    /// Display name if available (e.g. `"hProcess"` from the Win32 metadata).
    /// Empty when the upstream binding didn't expose a parameter name. We
    /// store `String` rather than `Option<String>` to keep the on-disk shape
    /// smaller — empty-string is trivially distinguishable at the consumer.
    pub name: String,
    /// Argument type.
    pub ty: TypeRef,
}

/// A reference to a type. The model intentionally stays minimal: consumers
/// only need enough resolution to drive the decompiler's display layer and
/// the arity-capping pass, not full C semantics.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TypeRef {
    /// Built-in scalar types.
    Primitive(Primitive),
    /// Pointer to another type.
    Pointer(Box<TypeRef>),
    /// Fixed-size array. The element count is stored as `u32`; the AST
    /// display layer that consumes this never needs sizes beyond `u32::MAX`.
    Array(Box<TypeRef>, u32),
    /// Function pointer.
    FunctionPointer(Box<FunctionType>),
    /// Late-bound named type; the archive guarantees that the name exists
    /// in [`TypeArchive::types`]. Unresolved names are flagged by the
    /// validator during load, not silently dropped.
    Named(String),
}

/// Built-in scalar types. Width is explicit (not `int`/`long`) because the
/// archive is consumed by the decompiler, which always works in terms of
/// concrete byte widths.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum Primitive {
    Void,
    Bool,
    Int8,
    UInt8,
    Int16,
    UInt16,
    Int32,
    UInt32,
    Int64,
    UInt64,
    Float,
    Double,
    /// Opaque character type. Distinct from Int8 so that `char*` can render
    /// as a string-like type in the decompile output.
    Char,
    /// Wide character (UTF-16 on Windows, UTF-32 on POSIX typically). The
    /// archive producer decides which based on the target OS.
    WChar,
}

impl Primitive {
    /// Size in bytes. Returns 0 for `Void` (consumers should not query
    /// the size of a void type directly — this is a convenience for
    /// iterating over typed fields).
    pub fn size(self) -> u8 {
        match self {
            Primitive::Void => 0,
            Primitive::Bool | Primitive::Int8 | Primitive::UInt8 | Primitive::Char => 1,
            Primitive::Int16 | Primitive::UInt16 => 2,
            Primitive::Int32 | Primitive::UInt32 | Primitive::Float => 4,
            Primitive::Int64 | Primitive::UInt64 | Primitive::Double => 8,
            // WChar is platform-dependent; the archive stores the actual
            // size on the producing side and callers that care should
            // resolve via the typed arg's observed access width, not this
            // method. We return the Windows-default 2 here.
            Primitive::WChar => 2,
        }
    }
}

/// Calling convention. `Default` means "whatever the platform's single
/// calling convention is" and is the common case on 64-bit targets.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum CallingConvention {
    Default,
    Cdecl,
    Stdcall,
    Fastcall,
    Thiscall,
    /// Microsoft x64 calling convention.
    Win64,
    /// System V AMD64 calling convention.
    SysV64,
    /// ARM AAPCS / AAPCS64.
    Aapcs,
}

/// A named type definition (struct / union / enum / typedef).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TypeDef {
    pub name: String,
    pub kind: TypeDefKind,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum TypeDefKind {
    /// A typedef alias: `typedef X Y;`
    Alias(TypeRef),
    /// A struct with ordered fields.
    Struct {
        fields: Vec<StructField>,
        /// Total size in bytes, including trailing padding as reported
        /// by the producer. `None` when the producer couldn't determine
        /// the size (rare — opaque forward declarations).
        size: Option<u32>,
    },
    /// A C union (fields overlap at offset 0).
    Union {
        fields: Vec<StructField>,
        size: Option<u32>,
    },
    /// An enum — discriminant type + named variants.
    Enum {
        underlying: Primitive,
        variants: Vec<(String, i64)>,
    },
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StructField {
    pub name: String,
    pub ty: TypeRef,
    /// Byte offset of this field inside its containing struct. Unions
    /// always report 0.
    pub offset: u32,
}

// ---------------------------------------------------------------------------
// Embedded archive lookup
// ---------------------------------------------------------------------------

/// Look up a single embedded archive by its stem (e.g. `"windows-x64"`).
/// Returns `None` when the archive doesn't exist in the embedded `types/`
/// tree; returns `None` (with a logged warning) when the archive exists
/// but fails to decode or is version-incompatible.
///
/// The stem list for a given binary is computed by
/// `reghidra-core::project` from `BinaryInfo`, since this crate sits below
/// `reghidra-core` in the crate graph and can't see `BinaryFormat` /
/// `Architecture`.
pub fn load_embedded(stem: &str) -> Option<Arc<TypeArchive>> {
    let filename = format!("{stem}.rtarch");
    let file = TYPES_DIR.get_file(&filename)?;
    match TypeArchive::load_from_bytes(file.contents()) {
        Ok(archive) => {
            log::info!(
                "Loaded type archive '{}' ({} functions, {} types)",
                archive.name,
                archive.functions.len(),
                archive.types.len()
            );
            Some(Arc::new(archive))
        }
        Err(e) => {
            log::warn!("Failed to load bundled type archive '{filename}': {e}");
            None
        }
    }
}

/// Returns true if an archive with the given stem is present in the
/// embedded `types/` tree. Used by `reghidra-core::project` during project
/// open to count available archives in status output without forcing a
/// full decode.
pub fn is_embedded(stem: &str) -> bool {
    TYPES_DIR.get_file(format!("{stem}.rtarch")).is_some()
}

/// Enumerate every embedded type archive stem in the `types/` tree without
/// decoding any of them. Used by the Loaded Data Sources panel so that the
/// user can see *every* shipped archive (not just the ones the
/// format/arch heuristic auto-loaded) and opt into the others on demand.
/// Stems are sorted lexicographically for stable display order.
pub fn available_stems() -> Vec<String> {
    let mut stems: Vec<String> = TYPES_DIR
        .files()
        .filter_map(|f| {
            let path = f.path();
            (path.extension().and_then(|e| e.to_str()) == Some("rtarch"))
                .then(|| {
                    path.file_stem()
                        .and_then(|s| s.to_str())
                        .map(|s| s.to_string())
                })
                .flatten()
        })
        .collect();
    stems.sort();
    stems
}

/// Find the index of the first archive in `archives` that defines a
/// prototype for `name`, mirroring the same precedence and underscore-
/// strip fallback as
/// [`crate::DecompileContext::lookup_prototype`]. Returns `None` when
/// no archive resolves the name.
///
/// Used by the Loaded Data Sources panel to attribute hits to the
/// archive that actually owns each function — a plain "lookup hits in
/// archive N" count would over-credit lower-precedence archives that
/// happen to also carry the same name (e.g. `posix.rtarch` and
/// `rizin-libc.rtarch` both define `malloc`, but on a PE binary
/// `windows-x64` is consulted first and any miss falls through in
/// the listed order).
pub fn which_archive_resolves(name: &str, archives: &[Arc<TypeArchive>]) -> Option<usize> {
    for (i, archive) in archives.iter().enumerate() {
        if archive.functions.contains_key(name) {
            return Some(i);
        }
    }
    // Fallback: strip MSVC-style leading underscore decoration. Mirrors
    // `DecompileContext::lookup_prototype` so the panel's hit counts
    // match what the decompiler actually resolves.
    if let Some(s) = name.strip_prefix('_') {
        if !s.is_empty() && !s.starts_with('_') {
            for (i, archive) in archives.iter().enumerate() {
                if archive.functions.contains_key(s) {
                    return Some(i);
                }
            }
        }
    }
    if let Some(s) = name.strip_prefix("__") {
        if !s.is_empty() && !s.starts_with('_') {
            for (i, archive) in archives.iter().enumerate() {
                if archive.functions.contains_key(s) {
                    return Some(i);
                }
            }
        }
    }
    None
}

// ---------------------------------------------------------------------------
// Bridge into the decompile-layer AST
// ---------------------------------------------------------------------------

/// Convert a [`TypeRef`] from the type archive layer into a
/// [`crate::ast::CType`] suitable for rendering in decompile output.
///
/// The conversion is lossy on purpose: `CType` is a narrow model
/// focused on what the C-like pretty-printer actually needs to
/// display. Anything `TypeRef` carries that doesn't fit (function
/// pointer signatures, multi-dimensional array element types,
/// struct/union references into the archive's `types` map) collapses
/// into a [`CType::Named`] leaf with a readable stand-in. The output
/// is stable enough for display but should NOT be used for layout or
/// ABI calculations — consumers that need those should query the
/// archive directly via [`TypeArchive::types`].
///
/// Size-sensitive primitives (`usize`/`isize`, `c_long`/`c_ulong`)
/// are already resolved at archive-build time by `tools/typegen`,
/// so this function doesn't need a target parameter.
pub fn type_ref_to_ctype(ty: &TypeRef) -> crate::ast::CType {
    use crate::ast::CType;
    match ty {
        TypeRef::Primitive(p) => primitive_to_ctype(*p),
        TypeRef::Pointer(inner) => CType::Pointer(Box::new(type_ref_to_ctype(inner))),
        TypeRef::Array(elem, _len) => {
            // CType has no array variant — degrade to `Pointer` to
            // match how C decays arrays at the ABI boundary. This
            // loses the element count but preserves the pointer
            // semantics that the decompile output cares about.
            CType::Pointer(Box::new(type_ref_to_ctype(elem)))
        }
        TypeRef::FunctionPointer(_) => {
            // We don't render full function-pointer signatures in
            // decompile output yet. Degrade to a generic pointer-to-
            // void so the slot still prints as a callable-looking
            // pointer and the user can tell it's a function pointer
            // by its name rather than its type.
            CType::Pointer(Box::new(CType::Void))
        }
        TypeRef::Named(name) => {
            // Defensive: early PR 3 typegen runs leaked a few
            // `syn::Type` debug-formatted names into the archive
            // (notably `Type::Never { bang_token: Not }` for the `!`
            // return type on functions marked `-> !` in libc). Until
            // those archives are regenerated, recognize the leak and
            // degrade to `void` so the signature line renders cleanly
            // instead of surfacing Rust debug gibberish.
            if name.starts_with("Type::") || name.contains('{') {
                return CType::Void;
            }
            CType::Named(name.clone())
        }
    }
}

fn primitive_to_ctype(p: Primitive) -> crate::ast::CType {
    use crate::ast::CType;
    match p {
        Primitive::Void => CType::Void,
        // CType has no Bool — render as uint8_t since Win32 BOOL and
        // most POSIX bool typedefs are byte-sized at the ABI.
        Primitive::Bool => CType::UInt8,
        Primitive::Int8 => CType::Int8,
        Primitive::UInt8 => CType::UInt8,
        Primitive::Int16 => CType::Int16,
        Primitive::UInt16 => CType::UInt16,
        Primitive::Int32 => CType::Int32,
        Primitive::UInt32 => CType::UInt32,
        Primitive::Int64 => CType::Int64,
        Primitive::UInt64 => CType::UInt64,
        // Float/Double aren't first-class in CType; render as
        // size-equivalent named types so the decompile output at
        // least says "float" / "double" instead of unk32 / unk64.
        Primitive::Float => CType::Named("float".to_string()),
        Primitive::Double => CType::Named("double".to_string()),
        // `char` is `int8_t` in most ABIs; preserve the name so the
        // user sees `char*` rather than `int8_t*` for string
        // parameters, which is the whole point of having a named
        // Char primitive separate from Int8.
        Primitive::Char => CType::Named("char".to_string()),
        Primitive::WChar => CType::Named("wchar_t".to_string()),
    }
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_archive() -> TypeArchive {
        let mut functions = HashMap::new();
        functions.insert(
            "CreateFileA".to_string(),
            FunctionType {
                name: "CreateFileA".to_string(),
                args: vec![
                    ArgType {
                        name: "lpFileName".to_string(),
                        ty: TypeRef::Pointer(Box::new(TypeRef::Primitive(Primitive::Char))),
                    },
                    ArgType {
                        name: "dwDesiredAccess".to_string(),
                        ty: TypeRef::Primitive(Primitive::UInt32),
                    },
                ],
                return_type: TypeRef::Named("HANDLE".to_string()),
                calling_convention: CallingConvention::Win64,
                is_variadic: false,
            },
        );
        let mut types = HashMap::new();
        types.insert(
            "HANDLE".to_string(),
            TypeDef {
                name: "HANDLE".to_string(),
                kind: TypeDefKind::Alias(TypeRef::Pointer(Box::new(TypeRef::Primitive(
                    Primitive::Void,
                )))),
            },
        );
        TypeArchive {
            name: "test".to_string(),
            version: ARCHIVE_VERSION,
            functions,
            types,
        }
    }

    #[test]
    fn archive_roundtrips_through_postcard() {
        let archive = sample_archive();
        let bytes = archive.to_bytes().expect("serialize");
        let decoded = TypeArchive::load_from_bytes(&bytes).expect("deserialize");
        assert_eq!(decoded.name, "test");
        assert_eq!(decoded.version, ARCHIVE_VERSION);
        assert_eq!(decoded.functions.len(), 1);
        assert!(decoded.functions.contains_key("CreateFileA"));
        assert!(decoded.types.contains_key("HANDLE"));
    }

    #[test]
    fn loader_rejects_future_version() {
        let mut archive = sample_archive();
        archive.version = ARCHIVE_VERSION + 1;
        let bytes = archive.to_bytes().unwrap();
        assert!(matches!(
            TypeArchive::load_from_bytes(&bytes),
            Err(ArchiveError::UnsupportedVersion(_))
        ));
    }

    #[test]
    fn load_embedded_missing_stem_returns_none() {
        assert!(load_embedded("this-stem-will-never-exist").is_none());
    }

    #[test]
    fn is_embedded_reports_absence_cleanly() {
        assert!(!is_embedded("this-stem-will-never-exist"));
    }

    /// Integration check: load the `posix.rtarch` archive that
    /// `tools/typegen` produced from the `libc` crate and assert it
    /// contains at least one well-known POSIX function. This is the
    /// end-to-end guardrail that catches postcard format drift
    /// between the tool-side data model (`tools/typegen/src/model.rs`)
    /// and the runtime-side data model (this file). If they diverge,
    /// decode fails here with a clear error before anyone ships a
    /// broken archive.
    ///
    /// The test intentionally doesn't hard-code a specific function
    /// count — the walker is expected to gain coverage in follow-up
    /// PRs and churning the expected count on every walker
    /// improvement would be noise.
    #[test]
    fn posix_archive_loads_and_has_content() {
        let Some(archive) = load_embedded("posix") else {
            panic!("posix.rtarch not found in embedded types/ directory");
        };
        assert_eq!(archive.version, ARCHIVE_VERSION);
        assert!(
            !archive.functions.is_empty(),
            "posix.rtarch decoded but has zero functions — walker regression?"
        );
    }

    /// Integration check: load `windows-x64.rtarch` from the embedded
    /// types/ directory and assert that canonical Win32 entry points
    /// resolve. This catches two classes of regression that the
    /// posix test misses:
    ///
    /// 1. Format drift on the `windows_targets::link!` macro path —
    ///    a change in how we parse the DSL would show up here as a
    ///    decode-time error or as an unexpectedly empty archive.
    /// 2. Data-model drift specifically for calling conventions —
    ///    Windows archives exercise the `Win64` / `Stdcall` / `Aapcs`
    ///    branches that libc never does, so if the `CallingConvention`
    ///    enum gains a variant without a mirrored update on the
    ///    tool side, decode panics here before it can ship.
    ///
    /// Canonical canary: `CreateFileA` from `kernel32.dll`. Every
    /// reverse-engineered PE sample imports it or something from the
    /// same symbol family, so it's the closest thing we have to a
    /// "load-bearing" function name for the archive.
    #[test]
    fn windows_x64_archive_loads_with_createfilea() {
        let Some(archive) = load_embedded("windows-x64") else {
            panic!("windows-x64.rtarch not found in embedded types/ directory");
        };
        assert_eq!(archive.version, ARCHIVE_VERSION);
        assert!(
            archive.functions.len() > 1000,
            "windows-x64.rtarch has suspiciously few functions ({}); \
             walker regression?",
            archive.functions.len()
        );
        let cfa = archive
            .functions
            .get("CreateFileA")
            .expect("CreateFileA missing from windows-x64.rtarch");
        assert!(
            cfa.args.len() >= 6,
            "CreateFileA has {} args, expected >= 6 (lpFileName, dwDesiredAccess, \
             dwShareMode, lpSecurityAttributes, dwCreationDisposition, \
             dwFlagsAndAttributes, hTemplateFile)",
            cfa.args.len()
        );
        // Returns HANDLE, which is a Named type alias resolved via
        // archive.types. Just check the return type is some Named —
        // we don't assert the exact name because the walker might
        // legitimately rename in the future (e.g. resolve the alias).
        assert!(
            matches!(cfa.return_type, TypeRef::Named(_)),
            "CreateFileA return type is {:?}, expected a Named type \
             reference (HANDLE or equivalent)",
            cfa.return_type
        );
    }

    /// Integration check: load `rizin-windows.rtarch` (sourced from
    /// Rizin's `librz/arch/types/functions-windows*.sdb.txt` SDB
    /// tree) and assert canonical Win32 functions resolve. The Rizin
    /// SDB walker is the third extraction path (after libc and
    /// windows-sys), so this is the test that catches drift in the
    /// flat-text key=value parser.
    #[test]
    fn rizin_windows_archive_loads_with_createfilea() {
        let Some(archive) = load_embedded("rizin-windows") else {
            panic!("rizin-windows.rtarch not found in embedded types/ directory");
        };
        assert_eq!(archive.version, ARCHIVE_VERSION);
        assert!(
            archive.functions.len() > 1000,
            "rizin-windows.rtarch has only {} functions; SDB walker regression?",
            archive.functions.len()
        );
        let cfa = archive
            .functions
            .get("CreateFileA")
            .expect("CreateFileA missing from rizin-windows.rtarch");
        assert!(
            cfa.args.len() >= 6,
            "CreateFileA in rizin-windows has {} args, expected >= 6",
            cfa.args.len()
        );
    }

    /// Integration check: load `rizin-libc.rtarch` and assert it
    /// contains a basic POSIX entry. Mirrors `posix_archive_loads`
    /// but exercises the SDB walker path rather than the libc
    /// walker.
    #[test]
    fn rizin_libc_archive_loads_with_malloc() {
        let Some(archive) = load_embedded("rizin-libc") else {
            panic!("rizin-libc.rtarch not found in embedded types/ directory");
        };
        assert_eq!(archive.version, ARCHIVE_VERSION);
        assert!(
            archive.functions.contains_key("malloc"),
            "malloc missing from rizin-libc.rtarch"
        );
    }

    #[test]
    fn which_archive_resolves_respects_precedence() {
        let primary = Arc::new(sample_archive());
        let mut second = sample_archive();
        second.name = "fallback".into();
        // Add an entry only the fallback carries.
        second.functions.insert(
            "fallback_only".to_string(),
            FunctionType {
                name: "fallback_only".to_string(),
                args: vec![],
                return_type: TypeRef::Primitive(Primitive::Void),
                calling_convention: CallingConvention::Default,
                is_variadic: false,
            },
        );
        let archives = vec![primary, Arc::new(second)];
        // Both archives carry CreateFileA — primary wins.
        assert_eq!(which_archive_resolves("CreateFileA", &archives), Some(0));
        // Only the fallback carries this — index 1.
        assert_eq!(which_archive_resolves("fallback_only", &archives), Some(1));
        // Underscore strip: lookup `_CreateFileA` should resolve via the
        // fallback path to the bare name in the primary archive.
        assert_eq!(which_archive_resolves("_CreateFileA", &archives), Some(0));
        // Truly missing → None.
        assert_eq!(which_archive_resolves("definitely_not_here", &archives), None);
    }

    #[test]
    fn primitive_sizes_are_sane() {
        assert_eq!(Primitive::Void.size(), 0);
        assert_eq!(Primitive::UInt8.size(), 1);
        assert_eq!(Primitive::Int32.size(), 4);
        assert_eq!(Primitive::Double.size(), 8);
    }
}
